[PHP]
memory_limit = 256M
upload_max_filesize = 20M
post_max_size = 20M
max_execution_time = 60
max_input_vars = 1500
date.timezone = UTC
expose_php = Off

; Error reporting (override per env in additional ini files)
error_reporting = E_ALL
display_errors = Off
display_startup_errors = Off
log_errors = On
